[package]
name = "DaochiClient"
module_roots = ["."]

[toolchain]
git = "https://github.com/ziranlang/ziran.git"
ref = "master"

[exports]
authorization = "authorization.zi"
authorization_owner = "authorization_owner.zi"
delegated = "delegated.zi"
async_delegated = "async_delegated.zi"
envelope = "envelope.zi"
account = "account.zi"
async_account = "async_account.zi"
async_client = "async_client.zi"
async_sync = "async_sync.zi"
auth = "auth.zi"
client = "client.zi"
crypto = "crypto.zi"
events = "events.zi"
keys = "keys.zi"
social = "social.zi"
sync = "sync.zi"
transaction = "transaction.zi"
url = "url.zi"
wire = "wire.zi"

[dependencies.oqs]
git = "https://github.com/ziranlang/oqs.git"
ref = "master"
